index:
    path: /
    controller: App\Controller\SecurityController::login

displayAllLocks:
    path: /displayAllLocks
    controller: App\Controller\MainController::displayAllLocksAction

displayLock:
    path: /displayLock/{serial}
    controller: App\Controller\MainController::displayLockAction

addLock:
    path: /addLock/
    controller: App\Controller\MainController::addLockAction
