index:
    path: /
    controller: App\Controller\SecurityController::login

searchLock:
    path: /recherche
    controller: App\Controller\MainController::searchLockAction

displayAllLocks:
    path: /displayAllLocks
    controller: App\Controller\MainController::displayAllLocksAction

displayLock:
    path: /displayLock/{serial}
    controller: App\Controller\MainController::displayLockAction

testSoluce:
    path: /testSoluce/{id}/{userSoluce}
    controller: App\Controller\MainController::testSoluceAction

displayContentSoluce:
    path: /secret/{id}
    controller: App\Controller\MainController::displayContentSoluceAction


addLock:
    path: /addLock/
    controller: App\Controller\MainController::addLockAction

editLock:
    path: /editLock/{id}
    controller: App\Controller\MainController::editLockAction

deleteLock:
    path: /deleteLock/{id}
    controller: App\Controller\MainController::deleteLockAction

profil:
    path: /profil
    controller: App\Controller\MainController::profilAction

deleteProfil:
    path: /deleteProfil/{id}
    controller: App\Controller\RegistrationController::deleteProfilAction

editProfil:
    path: /editProfil/{id}
    controller: App\Controller\RegistrationController::editProfilAction

displayAllUsers:
    path: /displayAllUsers
    controller: App\Controller\AdminController::displayAllUsersAction

promoteUser:
    path: /promoteUser/{id}
    controller: App\Controller\AdminController::promoteUserAction

jsonListCategories:
    path: /jsonListCategories
    controller: App\Controller\CategoryController::jsonListCategoriesAction

deleteCategory:
    path: /deleteCategory/{id}
    controller: App\Controller\CategoryController::deleteCategoryAction

editCategory:
    path: /editCategory/{id}/{newName}
    controller: App\Controller\CategoryController::editCategoryAction
